[package]
name = "boids"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
nalgebra = "*"
rayon = "*"
rand = "*"
crossbeam-channel = "0.3.8"

[dependencies.amethyst]
git = "https://github.com/amethyst/amethyst"
rev = "84707f7"
features = ["gltf", "vulkan"]