[package]
name = "boids"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
nalgebra = "*"
rayon = "*"
rand = "*"

[dependencies.amethyst]
version = "0.11.0"
features = ["gltf", "vulkan"]

[dependencies.shred]
version = "*"
features = ["nightly"]